// import "./globals.css";
// import Link from "next/link";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <header>
//           <nav>
//            <Link href='/ex01_home'>Home</Link>
//            <Link href='/ex01_sobre'>Sobre</Link>
//            <Link href='/ex01_contato'>Contato</Link>
//            <Link href="/ex02_produtos">Produtos</Link>
//            <Link href="/ex03_posts">Posts</Link>
//            <Link href="/ex04_posts">Posts Search</Link>
//           </nav>          
//         </header>

//         {children}

//         <footer>
//           <p>Meu site © 2026</p>
//         </footer>
//       </body>
//     </html>
//   );
// }



import "./globals.css";
import Link from "next/link";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header>
          <nav>
            <Link href="/blog">Blog</Link>
          </nav>
        </header>

        {children}

        <footer>
          <p>Meu site © 2026</p>
        </footer>
      </body>
    </html>
  );
}

